python:
	# expected output: 700, you can refer to the graph.png in this folder
	python max_flow.py < input.txt

cpp:
	g++ max_flow.cpp
	# expected output: 700
	./a.out < input.txt

generate-sample-directed-graph:
	sudo apt install graphviz
	dot -Tpng graph.dot -o graph.png
