python:
	# expected output: 1 2
	python battle_over_cities.py < input.txt
	# expected output: 0
	python battle_over_cities.py < input2.txt

cpp:
	g++ battle_over_cities.cpp
	# expected output: 1 2
	./a.out < input.txt
	# expected output: 0
	./a.out < input2.txt