cpp: 
	clang++-18  ./count_number_of_inversions.cpp  ../../utils/vector_utils.cpp   -I  ../../include/   -o count_number_of_inversions
	./count_number_of_inversions


python:
	python count_number_of_inversions.py


