cpp: 
	clang++-18  ./binary_search.cpp  ../../utils/vector_utils.cpp   -I  ../../include/   -o binary_search
	./binary_search


python:
	cd ../../../ && \
	python -m  my_implementation.chapter_02_getting_started.binary_search.binary_search



