python:
	# expected output: Yes 3
	python beads.py < simple_test.txt
	# expected output: Yes 3
	python beads.py < input1.txt
	# expected output: No 3
	python beads.py < input2.txt


cpp:
	clang++-18 beads.cpp
	# expected output: Yes 3
	./a.out < simple_test.txt
	# expected output: Yes 3
	./a.out < input1.txt
	# expected output: No 3
	./a.out < input2.txt


cpp_002:
	clang++-18 beads_v2.cpp
	# expected output: Yes 3
	./a.out < simple_test.txt
	# expected output: Yes 3
	./a.out < input1.txt
	# expected output: No 3
	./a.out < input2.txt